---
- name: Check action status
  uri:
    url: "{{ kafka_cloud_history_action_url }}"
    method: GET
    headers: "{{ kafka_cloud_action_headers }}"
    validate_certs: no
  register: kafka_cloud_action_history_status
  until: kafka_cloud_action_history_status.json.status in ["success", "failure", "canceled"]
  delay: 15
  retries: 30