---
- name: create configuration
  block:
    - name: create directory configuration
      file:
        path: "{{APP.CONF.PATH}}"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_user_group}}"
    - name: create file configuration
      file:
        path: "{{APP.CONF.FILE}}"
        state: touch
        owner: "{{app_user}}"
        group: "{{app_user_group}}"
    - name: create configuration file app
      blockinfile:
        dest: "{{APP.CONF.FILE}}"
        content: |
          test configuration file
      notify:
        - manuals
#    - get_url:
#        url: https://github.com/shikinadmi/gb_ansible/blob/master/README.md
#        dest: "/home/{{app_user}}/README.md"
#      notify:
#        - manuals
    - name: update configuration file
      replace:
        path: "{{APP.CONF.FILE}}"
        regexp: "(file)"
        replace: "file1"
  become: true
  become_user: "{{app_user}}"


# Установка NGINX и изменения конфигурационного файла по шаблону
- name: Install NGINX
  dnf:
    name: nginx
    state: present
# Теперь нам нужно настроить конфигурационный файл NGINX. Это можно сделать с помощью следующего задания Ansible:

- name: Copy NGINX template configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
...