---
- hosts: dev
  gather_facts: False
  connection: local
  vars:
    kafka_cloud_sa_id: "{{CR_KAFKA_CLOUD_SA_ID}}" # ID сервисного аккаунта
    kafka_cloud_sa_key: "{{CR_KAFKA_CLOUD_SA_KEY}}" # Секретный ключ сервисного аккаунта
  roles:
  - kafka
#  tags: kafka