---
  # Optimized GPT
- name: update configuration file
  replace:
    path: "{{APP.CONF.FILE}}"
    regexp: "(file)"
    replace: "file1"
  become: true
  listen: "manuals"

- name: install necessary utilities
  dnf:
    name: tree
    state: present
  become: true
  listen: "manuals"

- name: run tree command
  shell: |
    tree /home/{{app_user}} ; \
    ls -al /home/{{app_user}}/configuration/app_configuration.conf ; \
    cat /home/{{app_user}}/configuration/app_configuration.conf
  register: output_tree
  become: true
  listen: "manuals"

- debug:
    msg: "{{output_tree.stdout_lines}}"
  listen: "manuals"

...