---
# Optimized GPT

- name: "Install necessary utilities"
  package:
    name:
      - tree
    state: present
  become: true

- name: "Execute tree command"
  shell:
    cmd: |
      tree /home/{{app_user}}
      ls -al /home/{{app_user}}/configuration/app_configuration.conf
      cat /home/{{app_user}}/configuration/app_configuration.conf
  register: output_tree
  become: true

- name: "Print stdout_lines"
  debug:
    var: output_tree.stdout_lines
