---

# compose docker postgres
version: '3.9'

services:

  db:
    image: postgres:15 # pg_dump v15 ansible tasks
    #    container_name: postgres
    hostname: postgres
    restart: always
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "4"
    #          memory: 200M
    # set shared memory limit when using docker-compose
    #    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #    volumes:
    #      - type: tmpfs
    #        target: /dev/shm
    #        tmpfs:
    #          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    #      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    #      POSTGRES_MAX_IDENTIFIER_LENGTH: 127
    ports:
        - '5432:5432'
...