---
- name: create or remove testuser
  block:
    - name: create group "{{app_user_group}}"
      group:
        name: "{{app_user_group}}"
        state: present
    - name: create user "{{app_user}}" group "{{app_user_group}}"
      user:
        name: "{{app_user}}"
        group: "{{app_user_group}}"
        state: present
  become: true


Для создания БД postgres пользователей с помощью Ansible можно использовать ансибл-модуль postgresql_user.

Пример такой задачи может выглядеть следующим образом:

- name: Create postgres user
  postgresql_user:
    name: postgresuser
    password: securepassword
    state: present
    db: postgres
    login_host: localhost
    login_password: securepassword
    port: 5432
    login_user: postgres
...