---
#- name: Create Transaction ACL cloud
#  uri:
#    url: "{{ kafka_cloud_transaction_acl_create_url }}"
#    method: PATCH
#    headers: "{{ kafka_cloud_action_headers }}"
#    body: "{{ lookup('template', 'templates/kafka_cloud/kafka-transaction-acl-add.j2') }}"
#    body_format: json
#    validate_certs: no
#  register: kafka_cloud_transaction_acl_create_response
#
#- name: Set fact action_id
#  set_fact:
#    kafka_cloud_action_id: "{{ kafka_cloud_transaction_acl_create_response.json.action_id }}"
#
#- name: Check action status
#  include_tasks: kafka-cloud/check-action-status.yml