---
- name: List topics
  uri:
    url: "{{ kafka_cloud_order_info }}"
    method: GET
    headers: "{{ kafka_cloud_action_headers }}"
    validate_certs: no
  register: kafka_cloud_topics_list
  check_mode: no

- name: Set cloud topic list var
  set_fact:
    cloud_topic_list: "{{ kafka_cloud_topics_list.json|json_query(topics_query)|flatten }}"
  vars:
    topics_query: "data[?item_id=='{{ kafka_cloud_item_id }}'].data.config.topics[*].topic_name"

- name: Get diff between config and cloud topics
  set_fact:
    cloud_topics_diff: "{{ kafka_topics|json_query('[*].name')|difference(cloud_topic_list) }}"

- name: Set topic config to create
  set_fact:
    kafka_cloud_topics_to_create: "{{ kafka_cloud_topics_to_create }} + {{ kafka_topics|json_query(topics_query) }}"
  loop: "{{ cloud_topics_diff }}"
  vars:
    topics_query: "[?name=='{{ item }}']"

- name: Create cloud topics
  block:
    - name: Use cloud API
      uri:
        url: "{{ kafka_cloud_topic_create_url }}"
        method: PATCH
        headers: "{{ kafka_cloud_action_headers }}"
        body: "{{ lookup('template', 'templates/kafka_cloud/kafka-topics-add.j2') }}"
        body_format: json
        validate_certs: no
      register: kafka_cloud_topic_create_response

    - name: Set fact action_id
      set_fact:
        kafka_cloud_action_id: "{{ kafka_cloud_topic_create_response.json.action_id }}"

    - name: Check action status
      include_tasks: kafka-cloud/check-action-status.yml
  when: cloud_topics_diff|length