---
#- name: SET fact kafka_acl_topic_by_name_list (sort topic name)
#  set_fact:
#    kafka_acl_topic_by_name_list: "{{ kafka_acl_topic_list|json_query(acl_config_query) }}"
#  vars:
#    acl_config_query: "[?topic_type=='by_name'].{client_cn: client_cn, topic_type: topic_type, client_role: client_role, topic_names: sort(topic_names)}"
#
#- name: Get cloud ACL list
#  uri:
#    url: "{{ kafka_cloud_order_info }}"
#    method: GET
#    headers: "{{ kafka_cloud_action_headers }}"
#    validate_certs: no
#  register: kafka_cloud_acl_list
#  check_mode: no
#
#- name: Set fact cloud_acl_list (sort topic name)
#  set_fact:
#    cloud_acl_list: "{{ kafka_cloud_acl_list.json|json_query(acl_query)|json_query(acl_query_topic_list) }}"
#  vars:
#    acl_query: "data[?item_id=='{{ kafka_cloud_item_id }}'].data.config.acls[]"
#    acl_query_topic_list: "[?topic_type=='by_name'].{client_cn: client_cn, topic_type: topic_type, client_role: client_role, topic_names: sort(topic_names)}"
#
#- name: Get diff between config and cloud acl
#  set_fact:
#    acl_diff: "{{ kafka_acl_topic_by_name_list|difference(cloud_acl_list) }}"
#
#- name: Set fact kafka_cloud_acls_to_create (compare topic_names)
#  set_fact:
#    kafka_cloud_acls_to_create: "{{ kafka_cloud_acls_to_create + [{'client_cn': item.client_cn, 'client_role': item.client_role, 'topic_type': item.topic_type, 'topic_names': item.topic_names|difference(cloud_acl_list|json_query(acl_topic_query))}] }}"
#  vars:
#    acl_topic_query: "[?client_cn=='{{ item.client_cn }}' && client_role=='{{ item.client_role }}'].topic_names[]"
#  loop: "{{ acl_diff }}"
#
#- name: Set fact kafka_cloud_acls_to_create (delete empty topic lists)
#  set_fact:
#    kafka_cloud_acls_to_create: "{{ kafka_cloud_acls_to_create|json_query(acl_topic_query) }}"
#  vars:
#    acl_topic_query: '[?not_null(topic_names)]'
#
#- name: ACL action request
#  block:
#    - name: Create ACL cloud
#      uri:
#        url: "{{ kafka_cloud_acl_create_url }}"
#        method: PATCH
#        headers: "{{ kafka_cloud_action_headers }}"
#        body: "{{ lookup('template', 'templates/kafka_cloud/kafka-acl-add.j2') }}"
#        body_format: json
#        validate_certs: no
#      register: kafka_cloud_acl_create_response
#
#    - name: Set fact kafka_cloud_action_id
#      set_fact:
#        kafka_cloud_action_id: "{{ kafka_cloud_acl_create_response.json.action_id }}"
#
#    - name: Check action status
#      include_tasks: kafka-cloud/check-action-status.yml
#  when: kafka_cloud_acls_to_create|length > 0